services:
  # Base de données MySQL
  db:
    # buil:
      # context: ./db
      # dockerfile: Dockerfile
    image: ghcr.io/antoinereibel/voteapp-db:latest
    container_name: voteapp_db
    restart: no
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      # Tu n'as plus besoin de monter `init.sql` ici, car il est déjà copié dans l'image via le Dockerfile
    networks:
      - voteapp_network
    environment:
      MYSQL_DATABASE: voteapp
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: voteapp_user
      MYSQL_PASSWORD: voteapp_pass
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Backend PHP
  backend:
    # build:
      # context: ./backend
      # dockerfile: Dockerfile
    image: ghcr.io/antoinereibel/voteapp-backend:latest
    container_name: voteapp_backend
    restart: no
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - voteapp_network
    environment:
      - DB_HOST=db
      - DB_NAME=voteapp
      - DB_USER=voteapp_user
      - DB_PASS=voteapp_pass

  # Frontend Vue.js
  frontend:
    # build:
    #   context: ./frontend
    #   dockerfile: Dockerfile
    image: ghcr.io/antoinereibel/voteapp-frontend:latest
    container_name: voteapp_frontend
    restart: no
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - voteapp_network

networks:
  voteapp_network:
    driver: bridge

volumes:
  db_data: